### ISSUE TITLE
NullPointerException at resource.shipit.IssueJAXBSerialization.toExternalRepresentationIssueResource.getList

### ISSUE THREAD

**Issue by abstratt** [abstratt/cloudfier#108]
```
java.lang.NullPointerException
	at resource.shipit.IssueJAXBSerialization.toExternalRepresentation(IssueJAXBSerialization.java:29)
	at resource.shipit.IssueResource.toExternalRepresentation(IssueResource.java:489)
	at resource.shipit.IssueResource.lambda$toExternalList$5(IssueResource.java:478)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at resource.shipit.IssueResource.toExternalList(IssueResource.java:479)
	at resource.shipit.IssueResource.getList(IssueResource.java:115)
```

**Comment by abstratt** [comment]
Fixed.
