### ISSUE TITLE
 java.lang.NullPointerException at shipit.Issue.reopen (when no value provided for optional parameter) 

### ISSUE THREAD

**Issue by abstratt** [abstratt/cloudfier#109]
```
java.lang.NullPointerException
	at shipit.Issue.reopen(Issue.java:290)
	at resource.shipit.IssueResource.executeReopen(IssueResource.java:274)
```

**Comment by abstratt** [comment]
Model:
```
        if (reason != "") then
            self.comment(reason);
```

Currently generated Java code (which will generate a NPE if reason is null):

```
        if (!reason.equals("")) {
            this.comment(reason);
        }
```

**Comment by abstratt** [comment]
When the value is optional, we need to guard against null. We can generate safe code for equals/notEquals, but for the other relational operators we can't avoid an exception. We should actually forbid using them with nullable values.

**Comment by abstratt** [comment]
Fixed.
