### ISSUE TITLE
car-rental example failing generating code for precondition

### ISSUE THREAD

**Issue by abstratt** [abstratt/cloudfier#129]
This new operation when added to the Car class in car-rental, broke code generation:

```
    operation rentForCustomer(renter : Customer)
        precondition CarMustBeAvailable { self.available }
        precondition CustomerMustHaveNoCurrentRental (renter) { renter.currentRental == null };
    begin
        renter.rent(self);
    end;
```

```
java.lang.UnsupportedOperationException: TODO: auto-generated method stub
	at com.abstratt.mdd.target.jse.AbstractJavaBehaviorGenerator.generateActivityAsExpression(AbstractJavaBehaviorGenerator.java:66)
	at com.abstratt.mdd.target.base.IBasicBehaviorGenerator.generateActivityAsExpression(IBasicBehaviorGenerator.java:26)
	at com.abstratt.mdd.target.jee.JPQLFilterActionGenerator.generateTraverseRelationshipAction(JPQLFilterActionGenerator.java:74)
	at com.abstratt.mdd.target.jse.AbstractJavaBehaviorGenerator.generateReadStructuralFeatureAction(AbstractJavaBehaviorGenerator.java:163)
	at com.abstratt.mdd.target.jse.AbstractJavaBehaviorGenerator._doGenerateAction(AbstractJavaBehaviorGenerator.java:151)
	at com.abstratt.mdd.target.jse.AbstractJavaBehaviorGenerator.doGenerateAction(AbstractJavaBehaviorGenerator.java:321)
	at com.abstratt.mdd.target.jse.AbstractJavaBehaviorGenerator.generateActionProper(AbstractJavaBehaviorGenerator.java:61)
	at com.abstratt.mdd.target.base.IBehaviorGenerator.lambda$0(IBehaviorGenerator.java:113)
	at com.abstratt.mdd.target.base.IBehaviorGenerator$$Lambda$113/31877987.apply(Unknown Source)
	at com.abstratt.mdd.target.base.IBehaviorGenerator.runWithAction(IBehaviorGenerator.java:85)
	at com.abstratt.mdd.target.base.IBehaviorGenerator.generateAction(IBehaviorGenerator.java:117)
	at com.abstratt.mdd.target.jse.AbstractJavaBehaviorGenerator.generateAction(AbstractJavaBehaviorGenerator.java:56)
	at com.abstratt.mdd.target.base.IBasicBehaviorGenerator.generateAction(IBasicBehaviorGenerator.java:67)
	at com.abstratt.mdd.target.jee.JPQLFilterActionGenerator.generateTestIdentityAction(JPQLFilterActionGenerator.java:399)
	at com.abstratt.mdd.target.jse.AbstractJavaBehaviorGenerator._doGenerateAction(AbstractJavaBehaviorGenerator.java:184)
	at com.abstratt.mdd.target.jse.AbstractJavaBehaviorGenerator.doGenerateAction(AbstractJavaBehaviorGenerator.java:337)
	at com.abstratt.mdd.target.jse.AbstractJavaBehaviorGenerator.generateActionProper(AbstractJavaBehaviorGenerator.java:61)
	at com.abstratt.mdd.target.base.IBehaviorGenerator.lambda$0(IBehaviorGenerator.java:113)
	at com.abstratt.mdd.target.base.IBehaviorGenerator$$Lambda$113/31877987.apply(Unknown Source)
	at com.abstratt.mdd.target.base.IBehaviorGenerator.runWithAction(IBehaviorGenerator.java:85)
	at com.abstratt.mdd.target.base.IBehaviorGenerator.generateAction(IBehaviorGenerator.java:117)
	at com.abstratt.mdd.target.jse.AbstractJavaBehaviorGenerator.generateAction(AbstractJavaBehaviorGenerator.java:56)
	at com.abstratt.mdd.target.base.IBasicBehaviorGenerator.generateAction(IBasicBehaviorGenerator.java:67)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator.lambda$17(JPAServiceGenerator.java:656)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator$$Lambda$284/31699628.get(Unknown Source)
	at com.abstratt.mdd.target.jee.ActivityContext.generateInNewContext(ActivityContext.java:55)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator.lambda$13(JPAServiceGenerator.java:660)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator$$Lambda$282/28425636.get(Unknown Source)
	at com.abstratt.mdd.target.base.IBehaviorGenerator.runInContext(IBehaviorGenerator.java:155)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator.generatePreconditionQuery(JPAServiceGenerator.java:662)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator.lambda$12(JPAServiceGenerator.java:599)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator$$Lambda$281/10026940.apply(Unknown Source)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator.lambda$3(PlainJavaGenerator.java:155)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator$$Lambda$97/15107411.apply(Unknown Source)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.base.Joiner.appendTo(Joiner.java:108)
	at com.google.common.base.Joiner.appendTo(Joiner.java:152)
	at com.google.common.base.Joiner.join(Joiner.java:193)
	at com.google.common.base.Joiner.join(Joiner.java:183)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.join(IteratorExtensions.java:414)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.join(IterableExtensions.java:376)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator.generateMany(PlainJavaGenerator.java:158)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator.generateActionParameterDomainQuery(JPAServiceGenerator.java:604)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator.lambda$15(JPAServiceGenerator.java:555)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator$$Lambda$278/29709678.apply(Unknown Source)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator.lambda$3(PlainJavaGenerator.java:155)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator$$Lambda$97/15107411.apply(Unknown Source)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.base.Joiner.appendTo(Joiner.java:108)
	at com.google.common.base.Joiner.appendTo(Joiner.java:152)
	at com.google.common.base.Joiner.join(Joiner.java:193)
	at com.google.common.base.Joiner.join(Joiner.java:183)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.join(IteratorExtensions.java:414)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.join(IterableExtensions.java:376)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator.generateMany(PlainJavaGenerator.java:158)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator.generateMany(PlainJavaGenerator.java:150)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator.lambda$10(JPAServiceGenerator.java:574)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator$$Lambda$149/3918962.apply(Unknown Source)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator.lambda$3(PlainJavaGenerator.java:155)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator$$Lambda$97/15107411.apply(Unknown Source)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.base.Joiner.appendTo(Joiner.java:108)
	at com.google.common.base.Joiner.appendTo(Joiner.java:152)
	at com.google.common.base.Joiner.join(Joiner.java:193)
	at com.google.common.base.Joiner.join(Joiner.java:183)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.join(IteratorExtensions.java:414)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.join(IterableExtensions.java:376)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator.generateMany(PlainJavaGenerator.java:158)
	at com.abstratt.mdd.target.jse.PlainJavaGenerator.generateMany(PlainJavaGenerator.java:150)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator.generateActionParameterDomain(JPAServiceGenerator.java:576)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator.generateJavaClassPrefix(JPAServiceGenerator.java:124)
	at com.abstratt.mdd.target.jse.ServiceGenerator.generateJavaClass(ServiceGenerator.java:70)
	at com.abstratt.mdd.target.jee.JPAServiceGenerator.generateJavaClass(JPAServiceGenerator.java:163)
	at com.abstratt.mdd.target.jse.ServiceGenerator.generateService(ServiceGenerator.java:44)
	at com.abstratt.mdd.target.jse.EntityMapper.lambda$3(EntityMapper.java:225)
	at com.abstratt.mdd.target.jse.EntityMapper$$Lambda$141/7539216.apply(Unknown Source)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:1748)
	at com.google.common.collect.Maps$10.getValue(Maps.java:1793)
	at java.util.HashMap.putMapEntries(HashMap.java:513)
	at java.util.HashMap.putAll(HashMap.java:784)
	at com.abstratt.mdd.target.jse.EntityMapper.mapAll(EntityMapper.java:228)
	at com.abstratt.mdd.target.jee.JPAEntityMapper.mapAll(JPAEntityMapper.java:70)
```

**Comment by abstratt** [comment]
The code was temporarily removed so the example continued to work.
