### ISSUE TITLE
"ConversionException: Invalid format for date" in a query that takes date parameters

### ISSUE THREAD

**Issue by abstratt** [abstratt/cloudfier#99]
```
resource.expenses.ConversionException: Invalid format for date in 'start': 2016/02/01
	at resource.expenses.ExpenseResource.executeFindExpensesInPeriod(ExpenseResource.java:276)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by abstratt** [comment]
The expected format is: yyyy-MM-dd'T'HH:mm'Z'.  Maybe there should be a date and a datetime types. Or support for an alternative date-only format. Or we could just fix kirra-angular to send the date in the expected format.

**Comment by abstratt** [comment]
Also: resource.expenses.ConversionException: Invalid format for date in 'date': 2016-02-13T02:00:00.000Z

**Comment by abstratt** [comment]
Fixing so it too will accept yyy/MM/dd but that is really a bug in abstratt/kirra-angular#16.

**Comment by abstratt** [comment]
Fixed.
